name: pr-agent

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write
  issues:        write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    name: Run PR Agent
    if: ${{ github.event.sender.type != 'Bot' }}
    steps:
      - id: pr-agent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY:   ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          CONFIG.MODEL: o1-mini
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: "日本語を使用してください"
          PR_REVIEWER.EXTRA_INSTRUCTIONS: "日本語を使用してください"
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: "日本語を使用してください"
          PR_REVIEWER.INLINE_CODE_COMMENTS: true
          GITHUB_ACTION.AUTO_DESCRIBE: true
          GITHUB_ACTION.AUTO_REVIEW: true
          GITHUB_ACTION.AUTO_IMPROVE: true
          GITHUB_ACTION.PR_DESCRIPTION.USE_DESCRIPTION_MARKERS: true
